### ISSUE TITLE
loadAggregateView function

### ISSUE THREAD

**Issue by wbbarr** [GatechVIP/groupmeetingscheduler#17]
This function should take in an array in JSON formatted like the following:

{ total: 30,
 times: [[user1, user2, user3, user4], [user1, user2, user3,...],...]
}

and build the view data for the aggregate view

**Comment by pongad** [comment]
It just occurred to me that we forgot to talk about how what the user should do to make the aggregate view show. I'm just going to create a button to debug for now.

**Comment by pongad** [comment]
Aggregate view is done. Now we just need to work on what the user needs to do to bring up the view. How's the data thing coming along?

**Comment by wbbarr** [comment]
The load/save functionality is done, pushed on my master branch.

**Comment by pongad** [comment]
Still waiting for the data. The view itself is done. Currently displaying debug data.

**Comment by wbbarr** [comment]
I'm on it.  The past few days have been particularly nasty.
