### ISSUE TITLE
Uncaught TypeError when releasing mouse not over calendar space

### ISSUE THREAD

**Issue by wbbarr** [GatechVIP/groupmeetingscheduler#9]
There is an uncaught TypeError when you start selecting a region and then wind up releasing the mouse outside of the widget calendar area.  This results in trying to set the 'isTimeSet' property of an undefined element.  

Problem occurs on line 213, but probably occurs elsewhere as well.

**Comment by pongad** [comment]
This issue will be fixed when we pull Roberta's repo.
